/** De veelgestelde vragen van het eventoverzicht, Nederlands. */
export const eventFaq = [
  { q: "Wat is een online event?", a: "Een online event is een bijeenkomst die volledig digitaal plaatsvindt. Dat kan een webinar zijn, maar ook een conferentie, townhall, netwerkevent, training of strategiedag. Het belangrijkste verschil met een gewone online vergadering is dat een online event bewust wordt ontworpen rondom interactie, betrokkenheid en beleving." },
  { q: "Hoe organiseer je een succesvol online event?", a: "Een succesvol online event begint bij een helder doel. Daarna volgen keuzes over doelgroep, programma, werkvormen, techniek en begeleiding. Juist die combinatie bepaalt of deelnemers actief betrokken blijven of na twintig minuten afhaken." },
  { q: "Welke software gebruiken jullie voor online events?", a: "We hebben ervaring met Zoom, Zoom Events, Teams, SpatialChat en verschillende aanvullende tools voor interactie en samenwerking. Welke omgeving het beste past, hangt af van het doel van het evenement en de gewenste ervaring voor deelnemers." },
  { q: "Hoe houd je deelnemers betrokken tijdens een online event?", a: "Door deelnemers niet alleen te laten kijken, maar actief te laten meedoen. Denk aan gesprekken, polls, breakouts, gezamenlijke opdrachten, netwerkmomenten en interactieve werkvormen. Mensen onthouden vooral waar ze zelf onderdeel van zijn geweest." },
  { q: "Hoeveel deelnemers kunnen deelnemen aan een online event?", a: "Dat varieert van tien deelnemers tot enkele duizenden. De techniek is zelden de beperkende factor. Het ontwerp van het programma bepaalt uiteindelijk wat goed werkt." },
  { q: "Wat kost een online event?", a: "De investering hangt af van het type evenement, de groepsgrootte, de techniek en de gewenste begeleiding. Daarom maken wij voor elke aanvraag een eigen voorstel." },
];

export const eventFaqMore = [
  { q: "Wat is het verschil tussen een online event en een webinar?", a: "Een webinar draait meestal om kennisoverdracht rondom één onderwerp en is erg zendergericht. Een online event is vaak breder opgezet en bevat bijvoorbeeld meerdere sessies, netwerkmogelijkheden of interactieve onderdelen. Kennis wordt niet alleen door de spreker gedeeld. De inzichten worden ook gedeeld door deelnemers onderling." },
  { q: "Is een online event net zo effectief als een fysieke bijeenkomst?", a: "Dat hangt af van het doel. Voor kennisdeling, samenwerking en internationale bijeenkomsten biedt online vaak zelfs voordelen. Voor sommige vormen van relatieopbouw of informele ontmoeting blijft fysiek waardevol. Daarom kijken wij altijd eerst naar het doel en daarna pas naar de vorm." },
  { q: "Kan een online event hybride plaatsvinden?", a: "Ja. Daarbij is een deel van de deelnemers online aanwezig en een deel op locatie. Dat vraagt wel om een andere aanpak dan een volledig online of volledig fysiek evenement. Wij ontwerpen hybride bijeenkomsten zo dat iedereen gelijkwaardig kan deelnemen." },
  { q: "Kunnen jullie de volledige organisatie verzorgen?", a: "Ja. We ondersteunen organisaties bij ontwerp, programmaontwikkeling, technische productie, deelnemerscommunicatie, sprekersbegeleiding en live ondersteuning." },
  { q: "Hoe lang duurt een online event?", a: "Dat varieert van een compacte sessie van één uur tot een meerdaagse conferentie. De ideale lengte hangt af van het doel en de doelgroep." },
  { q: "Kunnen deelnemers netwerken tijdens een online event?", a: "Ja. Juist online zijn er verrassend veel mogelijkheden voor ontmoeting. Denk aan speeddates, thematafels, koffiekamers, breakoutgesprekken of vrije netwerkruimtes." },
  { q: "Kunnen jullie helpen met interactie en werkvormen?", a: "Ja. Dat is zelfs een belangrijk deel van ons werk. Technologie maakt een online event mogelijk, maar de werkvorm bepaalt of mensen daadwerkelijk betrokken raken." },
  { q: "Wat levert een online event op?", a: "Een goed online event brengt mensen samen rond een gezamenlijk doel. Dat kan kennisdeling zijn, besluitvorming, ontmoeting, betrokkenheid of het ontwikkelen van nieuwe ideeën. Het succes zit niet in het aantal deelnemers, maar in wat mensen meenemen na afloop." },
  { q: "Is een online event geschikt voor internationale deelnemers?", a: "Ja. Online events maken het eenvoudig om deelnemers uit verschillende landen en tijdzones samen te brengen. Daardoor zijn ze vaak efficiënter en toegankelijker dan fysieke alternatieven." },
  { q: "Waarom kiezen organisaties voor MeetingMasters?", a: "Omdat wij niet beginnen bij de techniek, maar bij de bijeenkomst en de deelnemers aan die bijeenkomst. Wij ontwerpen online events vanuit de vraag wat mensen moeten ervaren, leren, bespreken of besluiten. Daarna kiezen we pas de juiste werkvormen en technologie.", href: "/nl/testimonials", hrefLabel: "Lees wat opdrachtgevers zeggen →" },
];
