/**
 * Vervaagde miniaturen voor achter de hero's — GEGENEREERD BESTAND.
 *
 * Niet met de hand aanpassen. Opnieuw maken met:
 *   node scripts/hero-vervagingen.mjs
 *
 * Lees dit bestand alleen in servercomponenten. Doe je het in een component met
 * "use client", dan gaat de hele lijst mee naar de browser in plaats van het
 * ene regeltje dat die pagina nodig heeft.
 */

const VERVAGINGEN: Record<string, string> = {
  "/images/about-hero-desktop.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoUAAsAPwForE6rJiQiMAgBYCAJZgCdLwABYcDuMXX1Z6yoAP4I1hGojKHrZ0p3NsCXQAdhSkrAp8OFFrIyl8xeERzjhy2AoupK+9ism2J4aTHIbuBkbtuvOAof5NC5xW0PfVnYht6o5jDlLBBYAAAA",
  "/images/about-hero-mobiel.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJaACdLwABYsXzTnAgxwwAAP4I1hGojKHrZ0p3NsCXQAdhSlChPwJ1traDZKHyxmKl68ufPUWrlztW4nhpMchu4GRu2684Dv3FmrU+KIamd9nGLvujJG54WgAAAA==",
  "/images/about-hero.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoUAAsAPwForE6rJiQiMAgBYCAJaACdLwABYbvivBr7wAAA/gjWEaiMoetnSnc2wJdAB2FKSsCnw4UWsjKXzF4RHOL6hA5bwgcZ1Z/uRouwGpYorIr0WMRSYIpjxZrcf75W+vJ7nRC+9JQZg3beQAAA",
  "/images/blog/acht-grens.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAAoAPwFqrU8rJaQiMAgBYCAJYgCo9A3QHgAqg7RaSAsAAOAG1lDM7hv1PECB4JPAAqGqMPNcZaeOmH45EqaPIlFhR9J9RQxY6S0kT/dR6PeWqWuje4wQ7OY5KnVV/++Xnk9Nqs5D+flC1YwAAA==",
  "/images/blog/ai-paradox.webp":
    "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAAkAPwFqrE6rJiQiMAgBYCAJZwAAUqf6Hm8uSAAA/uzOzIjA8U5sRdepiEugszl0eVoyBIqeE3uhGezho8/yrwAAAA==",
  "/images/blog/blog-hero-desktop.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoUAAsAPwFsrU8rJiQiMAgBYCAJZQC/OBuCDshUzGB/JAAAsk3/t3NbubRoSacM2yljI0WV+VOXJNBM7ZvEyCpJBs0xihb31tnu5ayipQRXxCZBtv4QaDM8yleC4rL3wcsV5loqmqwAAA==",
  "/images/blog/blog-hero-mobiel.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZQC/OBuCFOjjnlRO7QAAALJN/7dzW7p1U0m6kuwokbuWKRkgXU3+3DA+sd8FGxqlSJ1uhFZWe/C4KirIevKKpj2+Dos42aN6Fs8HKnEYyWlAAAA=",
  "/images/blog/blog-hero.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZQC/OBuCFOjjnlRO7QAAALJN/7dzW7m0aEmnDNspYtAg7H8G2w2RzBgOt9/5aAwBfWSTz/Z9bAtgEGfRnEAnkTEjx4weUE7/veZtd0HUI+6S2AA=",
  "/images/blog/heen-en-weer.webp":
    "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoUAAoAPwFqrE6rJiQiMAgBYCAJZgCdAB9O+LDr6zA18/BUAAD+tAA6CDIQgQwRae8lJgekjW2BB4lQnBwznIYGXcMjuv+ENyBeCeEO89RLzRSk6ZfPCMVrarEY9u9BD6MbIv9MU6W1KVoRAye344IGmw2DZIAA",
  "/images/blog/niet-hetzelfde-wel-goed.webp":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdMoRwACnEHkWJoBxzMGwAAP60wP+TQFlrPgn7DPRPGLEkv4XxAsQk9k2J0QSuYxU5LoVOiXQCvjf0U7in18xueRMYwAA=",
  "/images/blog/olympiers.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdMoMYAChZ7TtBHXF3F/ywAPnzmn7jFDrxRKah8mT6gUAlCLFrwy2g47sn1uW5Gqn1B7GkkdoUc1Z71IjtOhLwDqQHxq8Yyic+cvJC8RjSvkSkSAAA",
  "/images/blog/online-beheersen.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAAoAPwFqrE8rJaQiMAgBYCAJZACsAA8aNZhN1S+nSwAA/uF2EoJaXnG5KyjhkFm+VSA8eepCdyUBhfTcrewGFpIxKgylwa23Wmk8rOU+tcXfknaTimaS/DDmPmucUgASdDGhHNGNlRAAAAA=",
  "/images/blog/rondjes-versus-vierkantjes.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAwCdASoUAAoAPwForE6rJaQiMAgBYCAJZAAAHGchrktl/AD+fWr+Sz8Vh9QRq12zbvXXO6eJWEXUO7lBMSOECQZr3XQWv/etMaTUTBA3NTMAXJko3B9G1ZpkbdWOh8AAAA==",
  "/images/blog/spel-is-nuttig.webp":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUAAsAPwFsrU6rJiQiMAgBYCAJZwCAAAioKJwe8ZHVD7qgAAD7jJJ34QTTSht9nOqaSvXDRaZTN+ommGTuQpo6/mu9iIT9tYeMRr9LwAA=",
  "/images/blog/stok-om-mee-te-slaan.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJagCdMoMYLIpz/4Dxto+81k97P3WWwAD91SLvu5uS7QdSnrtTi1euOug5bnFWqbaW9kxHLOo37YMAW3Wjesum/fJzpylhpU9HrD/08gSTbdfyL34o9qEKUDAAAA==",
  "/images/blog/systeemwoede.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAAoAPwForE6rJaQiMAgBYCAJQBOmUAAnexpJZOcl4AD+40tlfDuBWtD9lwMk3xmVgwQIEFy8yytoiHtdF4UyuaQuh+HwqB+uD0E03wAAAA==",
  "/images/blog/terug-naar-kantoor.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZQCdABTHEYj1c1V4gAD8NNnxLwfZ+FPbo6j9sDLR4AOEcMz5ng/2SlIxNR9GaeUFWXvkM4nNhejp1ZEmZ18kHPEfivGI+9eSiWHxKkqNzaAhra3kAAAA",
  "/images/blog/wat-gamers-weten.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBOmUABlXIkcz75Dwya6za4nQAD+sB8Xc8H62p2uYrX589+bAl4fL+er7WnLHY7C1ME4hs8OeWgagxGiPfgr2YPA1bvgsEQg2SWl1g12w+Fa6bLtEpLJlFN9OAAA",
  "/images/downloads-hero-desktop.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBOgAfGCNXeF99XAAP5nzYCpzMMhN5OrnJ54uileeANzp5EJcrRdlxAZafVvdaw5l9ShNL0O8yIWFVjUGfHR+pbyuLovJqMnydgxFg2ovXetMZTAAA==",
  "/images/downloads-hero-mobiel.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJQBOgAfFQIOoHb1gAAP5nzYCpzMMhN5OrnJ54uileeANzp5EJcrRdlxAZafVvdadnP+uWSnM6pmHcxzkLPEqLA41QS+q4N2P7DxoyiMYXvqQ5akQAAA==",
  "/images/downloads-hero.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJQBOgAfGBtOZLNuAAAP5nzYCpzMMhN5OrnJ54uileeANzp5EJcrRdlxAZafVvdaw5l9ShNL0O8zrtzHOQzUFCbyl3DQXJo4NanLyERwAgPmsXDJkOMAAA",
  "/images/downloads/checklist-alv-voorblad.webp":
    "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAgCdASoUABwAPwFwrFErJiQiqA1RYCAJZwAAPCTIAAD+7/VIXUFVZn6saqlgxF8ECjVp2IIBgTll7TgrRP5LsQjshCI0uHQAAA==",
  "/images/emilie-ad-v2.webp":
    "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAACQBACdASoUABQAPwF4tFOrJyUiqAgBYCAJYgC+wYw6WJwSASgF/3ApCSBHawAA4b8YKu5gfdvrJilIB2csP4O+waueHyb9q2SSkrJpAzpk89o0bGQ2w7jZ+sSZX+ZAoU+/8/jeFYriNlhDjDRh8cSXQkeygiUHkAB2w1XAyUF1dzknGVG6TkC2BF+B0Qm5CZywt3F7pXcXy+Ki0dW0jBpOtcb8I6E7zHBsXYAA",
  "/images/events-allhands-diversity.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAwCdASoUAAsAPwFqrE8rJaQiMAgBYCAJbACw7A/wAHwJYAAA+5TqzXZ7S4mMPfltD/wti07iA+L29QSihg7nVdTdwQtGTvAHwjX2jUu5EZOx4LUJYKPM/cmVbYEyEZC3Cr0xFNe4AAAA",
  "/images/events-allhands-hero.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBACdASoUAAsAPwFqrU8rJiQiMAgBYCAJZQDKACFsenS1BdI17RH3OWgA/u/QsJqAPxRupoDPS+fk6lJicCDODFWrbVebnW8vqbTLrIgUrpHJ38MVK6DUb/7apT3QafIrUoD0AAA=",
  "/images/events-allhands-koers.webp":
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdMoRwHuYt/8B3nDK2SeZXSQoigAD57GlWsRHmxJuTkNp9AkYVeNZJ9En8UqxeJPYhBNb7TMjK/ZznhCokMs80rsxdc1aNfhDfapfokYSdgDtD4XbLPhRgI37wiyqbmazsQgAAAA==",
  "/images/events-allhands-terugkerend.webp":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZwC/ODBhegAA/tt+35O9+6r2F/5RIa8fwTDEL7Vnb2AA",
  "/images/events-alv-hero.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoUAAsAPwFqrE8rJaQiMAgBYCAJaACdABDRSu0u9fhAAADZRP0b/YX0nhcvS8dlsCaHUj4W45e5caYuyAbo6LVYqNn8+DTfFKHPqu6NbzQWB31tVDbj+MVZPjUzo7Qvonqykodetkaa13yqAAA=",
  "/images/events-alv-praktijk-branchevereniging.webp":
    "data:image/webp;base64,UklGRrIAAABXRUJQVlA4WAoAAAAQAAAAEwAACQAAQUxQSBYAAAARF3D//4iIgSDbphnZ/dFOENH/CDsDVlA4IHYAAAAQBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBdiP/wFhPV/yUBpS78yAAD+0e2DQy0bbxiQudDTDvOBrrt5cwRP/HHBcy9cdfXs+jBJu7UjulBusvjOsJC9T5wXiRhYaNjF0ElB/m5LzQ1lpfIaJ2+lHnCQ0AAA",
  "/images/events-alv-praktijk-gewogen-stemmen.webp":
    "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoUAAoAPwFqrk6rJiQiMAgBYCAJQAALcKGuAH0MjQCxEPZK1gAA/sRr3VII0S/VUKPdZVcSi11K+u3y4mvBW8fTXbJ2OeezPz9ENakAqXEw3pD7FDdUT3TC7oZSP88FRxclFYpTYZjmL/E/Vmb9cgml3AAAAA==",
  "/images/events-alv-praktijk-jaarstukken.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJZQDImB9fcMe90TSxAAD+7VPdyDWq3R0hUAQdIPhhmXfqHF+Azv1g9EGzd8IA5P4LFrfVHjB5pVX+My54Olx7uvH4BYn/XYYAAA==",
  "/images/events-bedrijfsfeest-hero.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZgCdABMNkNWv1YXPKAD9xsr0uw1KHWsR3wil2yBL5W2E9ExC7+iaCB/E5i2L7CcX0xXjSC1n/4wsIhGLS0VF9sca+uZbHTdi2CgXzTxBF8gxSYwLTyMeOGypgAAA",
  "/images/events-bedrijfsfeest-praktijk-activiteiten.webp":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoUAAoAPwFqrU8rJaQiMAgBYCAJbACdMoRwL8AAcZEucpDooCSwAPqIdne69eCZ3QeeMUXcLxl6XwGAEe2k860q9lfaweLdFrR568LdsjMC3d1X6TWqY9mAdE6AGYT5fPtnkQDVT94l7/Ko65ux8KW+AAA=",
  "/images/events-bedrijfsfeest-praktijk-quiz.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoUAAoAPwForE6rJiQiMAgBYCAJQBYdg8TGoZpE+CZVCnNAAPzfYrdT0KX/3icIGNXqzH9+8twi/YfOAkCpqE/7YiKT6Lk93wl1OK8X87i2d7WS5wj7NYLd3GtC6sYky7WMwAAA",
  "/images/events-bewoners-praktijk-buurtgesprek.webp":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBYdg+xBao00Pdijq+iQAOICCRwnIJ/D2nGNQe8xSm3XW3vUkb4sr2W+wrUHA48WRT0IUnMr7oLLAUXrUHxcqYFl/os2TTY2AJ87gU0UcJe8DKi/qV2y4CYUgrB4AAA=",
  "/images/events-bewoners-praktijk-consultatie.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoUAAoAPwFqrU8rJiQiMAgBYCAJQBOgBFk4+X5eDZoAAAD87PD0auEkowNcmNYVLoaxG0v3xQVudlhbYglqcZQRvEx4otFWQXv+siXHvqvjkV6Pdi73fBttUA5Ai0gnHRVhARWBAAA=",
  "/images/events-bewoners-praktijk-huurders.webp":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBYdgj2CbzH8GOAA/I0TxA0p0FXhpCoHF5m7VD/eUzovD+WcJM9rZ0w8z014C3RulYL3c7s3HGHSjV0O+Qmf9MwIioHWQAA=",
  "/images/events-bewonersparticipatie-hero-v3.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZQAAHOCsNX7YeEAA/rCtUPjx4/ekH1ebPawmySWdKw63k4WgDZb1BoCQv26Hs2rVr6ya6f1X8ZB07KPZmDMXpbWpV2YQ6JbQCnYw62GQ0XhmAAA=",
  "/images/events-bijeenkomst.webp":
    "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoUAA0APwForE6rJaQiMAgBYCAJZAC7Ef/gPEGeuuYkjwnQAAD+1G0BCt0lb/hRAtBhX8T3wduwPQc387VNl7+OyZAVZxeQxcId+WuQrx3hngJ5PPtWujesJtj4gGK2Nwm4z9GU/TqZmOsnZ4W6N9jh0sgAAA==",
  "/images/events-brainstormen-hero.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPwForE6rJiQiMAgBYCAJYwC/OBoTkVwKUt4gqWoAAPyyHvIkrr/LpIt+WCiqgkhFtG5FjOF4Y/sprGjvkPCHbYTRJa4hb7y57txP/lA5UwRyntHAJulZs4ungIyJrChKGlAJJoAAAAA=",
  "/images/events-brainstormen-praktijk-campagne.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJZACw+BAANL1CEZ0gulXKgAAA/prrfrjwl9zUOqLT572Y3fdy97xGjWnEif/6YWSMbTRSCae36M6Z+zwX7tuQnZzkSvvSkUBlXKc4AAA=",
  "/images/events-brainstormen-praktijk-concepten.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJQBWAA8Rm/ClqcEWAAAD1c3VMa0cVkntdrR9PTe2xAFJboF0PvGq0ozmy/r5tsVcb9EI7m8NMqJnEYpJb5EqhuZcQLwU/SoAAAA==",
  "/images/events-brainstormen-praktijk-kansen.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJZACdMoRwACqgw/1JsE0TzfAAAP7lvSdhSbcq/dDCcFNncmJMIm0tWBD7m/OXCiEARnCvp+PVq9xQR727bABEiqeKIrj66j+wkAAA",
  "/images/events-community-hero-v2.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoUAAsAPwFqrU8rJaQiMAgBYCAJYwCsAB6VZOAEpmkV60AA/f0hz95n/oSXME2A/hixMBYqqBuAZunm+9mLN/Z64fXcXsZ32LKoR66nG++sV8TyPosHUzCN4REKuoNo64NBe64QvCoAAA==",
  "/images/events-community-olympiers.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoUAAsAPwFsrU8rJiQiMAgBYCAJbACdACDTm8+KpATJwBgA/j7Qbr2DTaalqQhgk1KvFVe91QDbKX5Bgfm0E/TQG6AwwPKx1+8PsFhOw1tEjKruKi7JF3QSH+MFDylzrpQEGJAugAA=",
  "/images/events-community-professioneel-v2.webp":
    "data:image/webp;base64,UklGRp4AAABXRUJQVlA4WAoAAAAQAAAAEwAACgAAQUxQSB4AAAARFyAWTOb/hJxGRISDggBkGCWVVJPdBBH9T77JqABWUDggWgAAAHADAJ0BKhQACwA/AWqtTysmJCIwCAFgIAljAABTNy8wcGHRwAD+5sq6orivTYIdVUjLEvoC7ZhcT38c+VT03Cp5ntIdC9+Z9/5tlAMcWx6fbM5gAfGAFMIgAA==",
  "/images/events-community-terugkerend.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoUAAsAPwForE6rJaQiMAgBYCAJZAAAXuazLmpC8y6uRCQGgAD9d7v1c1QRyJl7aVLSrzp5SC5uhAxzJBAQirHz/6qp2qKP+DLVK3t7+ssMOZbaCN5Egy+hhTWrqDHxoKTLAAAA",
  "/images/events-conferentie-hero-v2.webp":
    "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoUAAsAPwForE6rJaQiMAgBYCAJQBadBH91kKWLnQ955PqSWAD+5soaqugHeLOI5vs6L55rdqX/ZMGC+5xqiPZkcpjSl5jSF6mwztbyClmqiumnde1Q3XEyWa5eWu68yRvdm5eDKKhHvBXMfeBr60GMXySwoxkO5GETQAAA",
  "/images/events-conferentie-praktijk-brancheorganisatie.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAAoAPwFqrU8rJaQiMAgBYCAJYgCdABriWq8GjDr78sAAAP6ws9sWTqwVdrZ68XL7FeghIQSq01zaGpYXbrIoaY2zK0p/gCuuB5rFqO2pYfZ/k3fakyPlD86AAA==",
  "/images/events-conferentie-praktijk-hybride.webp":
    "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoUAAoAPwFqrU8rJiQiMAgBYCAJQBOmUABsbkpaNXR0bShAAP7tWsoT+rBYKJIdvSWHZWO0s1n4A1zN08WkJJkSC1Y7SmkwxoQNyOWVQllxiB51n8G+BPKRt9aYTPkWA9xzSntOgM8DxB3lNM4vOsixVihJU5pCAAA=",
  "/images/events-conferentie-praktijk-meerdaags.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJYgAAP/lxz+X2gbQA/jGNN4R3tP/+YHeAVJjpiwXgLgKhotwi1DErAZQBGrlMkyt7/vWmNZB/CWudzREOoMeMeY9H/JIHqscYsAHafHZ4AA==",
  "/images/events-focusgroep-hero.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJQBdgA6QtzQ5XTRk4hQYAAPzYn1O+W0hvOS1mAVrpO9S1kXxkgw4HEJeEta90uPxOE3r8gN7kZqC9Mi8CvJKSxoV/uvU6c1ShN1/E/jgaUbwKFUlQAA==",
  "/images/events-focusgroep-praktijk-concept.webp":
    "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoUAAoAPwFqrU8rJaQiMAgBYCAJZQC7AAp+mAD8ULyVjH+rFyJ98e2m5Py1uAAA",
  "/images/events-hero-poster-mobiel.webp":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZgCw7BKgJ2z1zdSrtAAA8ZtzP9QWZFc4bAu6SyBQiVjXcefn39NgZAeEWXyyMZsr2O17MhwSY/2BC2gXSqjBf6MMm+2fwAA=",
  "/images/events-hero-poster-v2-mobiel.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPwFqrE8rJaQiMAgBYCAJZgCw7Arxgg5iBNQEAAD6YbTfCVJLqRijQ79/zk0rOmdHJmUPknLbl61gd/XC2uP6rNQkURakgXct/BiXTCMbesP02nsGKWwAAA==",
  "/images/events-hero-poster-v2.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZgCw7ArLDfvakNBQ4AD6YbTfCVJerYfMz6YTb4d2BbI1r10BZeL65bwOs6B1wtrj+qzUJFEWpIF3LfwYl0wjG1mDdTRsIhQYAA==",
  "/images/events-hero-poster-v3.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJaACw7ArLDfvakNBQ4AD6YbTfCVJerYfMz6YTb4d2BbI1r10BZeL65bwOs6B1wtrj+qzUJFEWpIF3LfwYl0wjG1mDdTRsIhQYAA==",
  "/images/events-hero-poster.jpg":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJaACw7BMtVl3g2IvDlwIAAPpnf5iOZ++KOM6BXKEtskoR/5/uVPz/g3KCH4NAsgY7VnWPZt7Q4JMms9AIldVKihINNEwAAAA=",
  "/images/events-hero.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwBACdASoUAA0APwForE6rJaQiMAgBYCAJYwC7GuAt/8B6FI1H1RGAnD2ZAAD+Tr/McPPDL7EjtVE16PF6vd5bderPS5Ae97PtkNZ0Gi6Fn0gk0peNMYfscObrdvyij7KXlxwbkUmVE7gUGAA=",
  "/images/events-kerst-hero.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJYgCdACICXTFuAeiPsIAAAP5pozhKHsowK9qiTDXVxjpxJtKHe3DXiaSOZmB5slGFPJKabrCdlUYVjG/3Nvml5AWcl/2RUSmiQ5u+PppkHBd2AAA=",
  "/images/events-kerst-kerstquiz.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJbACxC8ACDyujNtlWOC8AAP4zn69Cl9OBFOlpMSgmTTDm6kO01vl8Xqx1hVVntFFW5kcnikIi9w/I/6cOvsFhig3SyVoeB1fDLIFhuToMSt1ouHdMJ47QAAA=",
  "/images/events-kerst-leveranciers.webp":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZQDE2BuvnHAyT/g4GmsAAPzi8AqYPDw3XUBKa6rVrJijjBjY1JMFEBr8b3pVNHLU55YD+/mAlO7fRS/qaYgA",
  "/images/events-kerst-stemmig.webp":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJYwCdABPSz3WtuAAAzYW9QmJKKYF0R1/oRnvIW2wUo84tc4lY3y6b9Dm61ByJAAA=",
  "/images/events-klankbord-praktijk-heartbeat.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAAoAPwFqrU6rJiQiMAgBYCAJZQAAYXBl3961liMAAAD+xa6ZBUYHh9zwj1UXc1U3txHVuu4txfORTcBvjp0+bzjwUjnvWyfWHdGMVf9hhiBpujWoqzIQ74jqmL2rRuBg5Pku7pXvNAAA",
  "/images/events-klankbord-praktijk-stakeholders.webp":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUAAoAPwFqrE6rJiQiMAgBYCAJQBgbhDa4Lh5M1yewkw8q4AD+6ozkIa4UmXD6SdRMSvRVH1XUxFIfU451+31FXWGJiB+rzJc/DnYAAAA=",
  "/images/events-klankbordgroep-hero.webp":
    "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZgCdMoABWGikTz0uH28IAP7prSDQ/GjAmNAoNjpr/jeuerdbZP0IblPbtmo/1QyYvJLkEKmhQI2VKJoBmmbuqNm8/BdJQgKLy89MgLxNJ4r0b4e1tK6txl/rUvOEj/fAAA==",
  "/images/events-netwerk-praktijk-alumni.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAAoAPwFqrU8rJiQiMAgBYCAJQBOgBFE6Ln7FapfuYbAAAP5JpIABu73UodkTRst5i1IEeTq/OHjayTPv8TSBcqIrreaXsypiGrtKmKql+kYtJZNSpUrRHdgAAA==",
  "/images/events-netwerk-praktijk-clubhuis.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBOgAybGqLlAgfEHzYgA/ogxO3MUkXkN8RmRP+jNsxU4OpL5nIGjyx6XExxcySgZk93TfFH/1bdqKZjvIsZ27bd6ve2gknmroo9nNtMNREhFxJgAAA==",
  "/images/events-netwerk-praktijk-conferentie.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJbACsLwABkWuettZy8HgA/urIvDiMNONGtwxyhqxM45BbHVFsAp3tGIRsC9Z7AYH0dPIpEf3YhyAZ8nsMpCGgfCTWM5aShAvhNHbdnhJ56kUbA2W80LUXxDXyzAAA",
  "/images/events-netwerkevent-hero-v2.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoUAAsAPwForE6rJaQiMAgBYCAJYwC+SBwp0DXOc6tK7tE0AAD9d0bXITMFJ0+E6fKb8vYGFRFATd9Ce5nxwkG5M0Ij0o1arysA6x/EmwfglT+3lsIye4T7t31CUTRHt7TaOBCw0Bf4syqlvwAAAA==",
  "/images/events-onboarding-praktijk-ervaring.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBOmUABG494/f9Ok2KgA/XhCM9QD/Gy8PKZc6JR0rNdzQkCVHlBR9vOtGk/xWFwJy3aUpdUTGobAJX5wYpmmTsZ62Jin0UuXtwAA",
  "/images/events-onboarding-praktijk-internationaal.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJQBOmUAAdFfkctQAA/rYFdtWpMPSfowzKMFcZSwAaOb0KJU7IalfZZHRybQ/5E2OrtIx7EGrdn+t1Mq1S+bzf0Om2i8WR/JubfDGtcFL0IAAA",
  "/images/events-onboarding-praktijk-maandelijks.webp":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAoAPwForE6rJiQiMAgBYCAJYgCdAB7AfZ5zNPyp8MAAzHnQN6VZX7KjREiTPMxmhtA/yP4PF3mFVjEodT8t96A68QdUtU5BObTkEAYHgAAA",
  "/images/events-onboardingdag-hero.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJZQC7AB6JiU96I1jjSz8slQAA/tRqYKz3SDljKkOQ0npzX5kbr2syB2oAYZnd1FWw5HbCoqJzTT0bobwStd/BzYl4HUaAcnPs7lCYGvDzrc7jAAA=",
  "/images/events-open-space-hero.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAAsAPwForE6rJaQiMAgBYCAJYgC7ABkwWEvWxdZ4H4okAAD+1tks2fGfKwW3u08mr9ZKFV7zmRI+TAaIz7rjk0qFk7zyspYr1pQQOI4DvxQcK/uiGkceFblB+b+7Qd7stquOBFs9aoYAAAA=",
  "/images/events-openspace-praktijk-community.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZwAAP/R/20ulv0mTmgAA/B4CB1J2NXPPlpz4MtoBjvffaOpc+inuWtnmMIhjmKdiCZ7IfKU7atnlUS4DNlMVDlVYof+c1u6fEtb4WYWQAUt0J+A1lxCDLgAAAA==",
  "/images/events-openspace-praktijk-innovatie.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJZACdACPQf9JS5BdCAIW6+AAA/gSWTmvPeNZP2Bmxnx6YB359onChmTFdVtdsX1cbRK0vvlW+YPm0LpEyCUsadq/DBzt/diesGasg72/gAAAA",
  "/images/events-openspace-praktijk-verkenning.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAAoAPwFqrE8rJiQiMAgBYCAJQBWAAYdEn9eEy5DgAADxAEIqIG5MfjNknm8LplNIrx/W2hAqfMkm59+Tv2DPnp/Kt1d1DoPo3LAT7m8NolOkkziIsgN0o0cC2lhsRdZ72XgA",
  "/images/events-praktijk-branchevereniging.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBgfeABKPIke9K5waGxIAP5PdNzpFzBj4TmNVfRO6Oy3QFvZUU3F+MDvLg5GSJLT/5N36om7X4BTT8lMFNATuYmKqSI0kkITkg3O1v6ZtTkSlcWLm+gYb8qZkAAA",
  "/images/events-praktijk-forum.webp":
    "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAgCdASoUAAsAPwFqrE6rJiQiMAgBYCAJYwAAQPu0AAD+3r8QTyscWTn6gxOeu6tDGioOhn3vdyNyAAA=",
  "/images/events-praktijk-whiteboard.webp":
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoUAAsAPwFqrU8rJaQiMAgBYCAJZQBTAAbcBUfL2S6LIAD+tRXF/AjYbb5xu2Va1KO/h1P131CVAhjadQWwecT2k398qyJFU7ElsW0UavnAPTZ7C+7F/1ZnpHZ/u10Q0Z5253u2V0UUElGFH10luFI1xVL/AP5KwoAAAA==",
  "/images/events-spatial.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAAkAPwFqrE8rJiQiMAgBYCAJZACdACIZW1Sjy/QA/rIj9mYiqiFABcnr10+YFvf6Lo9XJQO/o5KTzsWMQ909QlDQPyBTCcSkKo2CgKGp8CU3+DAiwyAA",
  "/images/events-strategiedag-hero.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUAAoAPwFqrU6rJiQiMAgBYCAJYwCnFCPoP5gEl9Qd1ORLAAD8EEGj6/76nfXZnGiczPmLUQ92KS9MotkEJsFkSCh5QcqlEVKhhukvROOax0LutRQ8iGDySCfON3COVU9DIvVkHuygAAAA",
  "/images/events-teambuilding-hero-v2.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBgbgf5Jz6w4vGgA/q1ucGwNp/OhbvnicsV84vHTo9cY0jIcgFshja5bR0/08NYiGjY3D4I0QRWwZRSF5/BG+8baZgNW5r0y03nezgYtAU0TQAA=",
  "/images/events-teambuilding-praktijk-hybride.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAAoAPwFqrU8rJiQiMAgBYCAJYwDE2CM/X6S78n22Ru2wAP5PpRNEyWT9zw/IGF4VrrtJzsFe9nZpCWcSNjlnGaH6SoSBJ25oWanvMhskV6IS6L3Tnff32sHdt+x0RwBzPRNT06QguAAA",
  "/images/events-teambuilding-praktijk-internationaal.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoUAAoAPwFqrU8rJaQiMAgBYCAJYgCdMoADTpJG+PtgGYY9PVwAAPxhKbyxeKNVdNq80MPVq7cZzTRjgnifYgqY19bZKyojVUl9nHXV27OvirymsUhAAA==",
  "/images/events-teambuilding-praktijk-kennismaken.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAAoAPwFqrU8rJaQiMAgBYCAJYgCdACIj6OTqZjwQUAgAAP6iknvI6c1ooo77nAXMFSEkets6Qeo9Uf1vxIfaRTVPEtznzvtKpbx41gKxjmEVQAAAAA==",
  "/images/events-teamuitje-hero.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJYgCdMoAC/qzswimxoCRFwAD+1hhtc9/s+yDMmbaSqa0B8stOcDmM3fybDP9pF9E68EP52JmCGlCo9P5xT8DZnEgm5ulAP9bJRc737Q9MMYYwAAA=",
  "/images/events-teamuitje-praktijk-energie.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAoAPwForE6rJiQiMAgBYCAJQBOgBDechnlXj6vqAAD+mPb+w0vajMPYoQskIVJnlAK3F90Lm81sLy9JcfB3gFe2ACHJit1swsivumwmnf88mLZ9JPp1Av8gAA==",
  "/images/events-teamuitje-praktijk-escape.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZACdMoADPLHXjbH28Fi4AP7p64vviAeJdLFXWv+CES2UdE1afFadsKiv7KrLrqloivRSngoysVN2kke2gId0SZoo7QwahfRGLh+tWCy9gi/Ucm5UdKE65QTCAAAA",
  "/images/events-teamuitje-praktijk-terras.webp":
    "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZACdL1yB2rp36HGKUwEAAP7elNwi/O0lHX797zLplDcjy/qDojC9wWZ1EYDYLhOR64xmLrXW9xodQqMEEQuHSIxqQjfJOjZ5BH2OMcMU4TN0N/+OuepobaGolX8laR+FaLgUcAA=",
  "/images/events-townhall-hero.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJYgCw7BkIhTreT+UE+oAA/P1y9Q0i1z7OkPiUTf8g4bBrK7geg28AJk9OuULoaoaN/qPFkk4XzFKfub/Ww60mRkQnZEIdC/BJwSqFM8eAAA==",
  "/images/events-townhall-praktijk-directie.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwAwCdASoUAAoAPwForE6rJiQiMAgBYCAJZwAAMAJHImyAAP7XVPhhsqponXfgcZlPwmXg9Q2sAzgwrscElNBw8ui2eGhbD/SuLoVJs7YVr9mnCCH97n9U+cMp2sKeBxg42Ib8OL0NWSRf7k5gw8gA",
  "/images/events-townhall-praktijk-internationaal.webp":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAwCdASoUAAoAPwForE6rJaQiMAgBYCAJQBOmUABH2OYQjpJZogWAAPxdX+S7I4HIBFkvlPsimYcd6IgkXU572ARIq4mIAAA=",
  "/images/events-townhall-praktijk-verandertraject.webp":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoUAAoAPwFqrU8rJiQiMAgBYCAJQBahGQBgVrCpihV0AP62VIzq3fJ+ildnzL1ve3JmgKrmgouEYX0QMVrccGNI2NsEqVAfo+SSCkRI9P/yAAAA",
  "/images/events-training-praktijk-bekendheid.webp":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZwC90CKUbCPe6HIAAP7emej8rxqu6j29OUrPzO7n3LNNdpkIyAAA",
  "/images/events-training-praktijk-cohorten.webp":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoUAAoAPwFqrU8rJiQiMAgBYCAJbACdMoR7X6B+KoBYF7nnSOxcVfAAAP0U2u+cJ1qn4xKejDtf5qvoNbXkf8FdcXVvv9kEvvFa/88/z8rddZOQ5Ha5GY4JibazX4tlBRE8M/vojnGe141T9iXXdPF8AAA=",
  "/images/events-training-praktijk-trainers.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAAoAPwFqrU8rJaQiMAgBYCAJYgCdACG832nP7kJQXCFAAP7VWFoRy6nlgj1ERY2Ixx/cJscQhvJqFYnHTpEM12j7BrvnCT04kCFF9+kqfwqocz6DDHaKOUAAAA==",
  "/images/events-training-workshop-hero.webp":
    "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJQApggdUBcQt3MobLHLZjj8AAzj9DK1gWzxGCyxTa8IxQi72MsbrTH4I8mun3RnVt6t3D4rP9iPvhnAJ5viTb6M0iQIdCTieRfd7fhREEnyFj8ox4QXyl+biWaBCy+KOhIy0AAAA=",
  "/images/events-webinar-hero.webp":
    "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBdiP/wGh99ctX0TrgzB6sLgAP5PjVkWcCbgWa+0bStIBo68x1sqwc8BQg/lcffdWtVUpqTjy2T6nRYfaB4ly/OBtlpXr1TqCiVOX/rCuLrUZTGJjtH7B/zlusgJrSoAAA==",
  "/images/events-webinar-praktijk-gesprek.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAoAPwForE6rJiQiMAgBYCAJZgC7AB2+b6WnFJ7RP2wA/jq+tRotc2SvnnbN53UiTrvbcIZEoABahwabuStMC2TNRHx/WLL1ovBBN2Xv7rUUQa8ejQdPCYyblEEc7AAAAA==",
  "/images/events-webinar-praktijk-leads.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAoAPwForE6rJaQiMAgBYCAJQBdgBDrvXkAesi+2ugAA/pPERef66YiCkNVcbyOS0iiOjsza5yaVtNI6qS6IvDIUt6W0KNzB6Zxs7yBwL74Rkec18ssrtHlsDEMO9AAAAA==",
  "/images/events-webinar-praktijk-leren.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAAoAPwForE6rJaQiMAgBYCAJbACdMoRwACD8nsa1Ekpq4sAA906D/x30zcJgdLA+scvhBP6kW4RQ6TmbmPdm7REbf3+PL0839+sv14DMhOj1O8zjpNu43bMl8Kn+qUt+7L9OG2cBAAAA",
  "/images/events-world-cafe-hero.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZQC+SBtoaXHPUKuMtAAA/lR4Wuw13rWZEqpX0riNi/niLXQqmLrglkxoJH/fV3fzpb6kUk7RjSfMAn/s6D0qM/vhmdf3JlY/mCJd0vzJ2HAA",
  "/images/events-worldcafe-praktijk-ervaringen.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZwC2yA6xHwfD6cAA/t8H4dZ7LjDbeBmufFr2JZ8Dtib0Y6rBAMyuFlzSJm2bbG6oooWYcwXbs7FOLtYHY7LkKo2gq1MROUin0FuCgcETD6IIwAA=",
  "/images/events-worldcafe-praktijk-inzicht.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJZQAAW+li82DbAAD2v47dZeIUTYbFYO0l8+UTbOUZBXcLj6fbsrqVUo0IQPf+9GjEdoGDtzbqmwwQ/vpXpBYNKRT5zZITwccAAA==",
  "/images/events-worldcafe-praktijk-leren.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUAAoAPwFqrE6rJiQiMAgBYCAJajuAHWeQtE0KKStpyRi+AP7th5Fwcqol+fEzhxXk0RjWRkhejdUZfbeTOUEXrvXGOk1/xgcN/GP2t/xSpoSw2fFiz2v0pjKQ7FoAAAA=",
  "/images/format-1.jpg":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJYgC7MoADRuTz7jhmNaUAAPZwHTv5anYYgMLx64A1k3qmevOQqrx1C0QYXJFxdNdOUHEhS3YJKqwH07qDechaz7UW6Dgkrpg7FYByJHpxcPIkso51RHRAAAA=",
  "/images/format-2.png":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAA0APwFqrE8rJiQiMAgBYCAJZwAASTmT2sKRfeeAAP7fSYBcg2XXhwz6OXUeVIjZiZtp4DwJqcz/AlRDVukDIxSD8WPTvrDv8PtY+r976t4vVnibrAAA",
  "/images/format-escape.png":
    "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdMoR4GBpTC8y0n39qjJkAAP55OT51ypBXnnKICc93v6KkPHEC4OvO7yFO/4kL2mLirE67k/t/0LCHvPRD768rWOFPgUC1bhNfuFHo8XFu7/A02HnrAyOE/4YewIS4edFYrFZyN6ZLtL83s/X6AAA=",
  "/images/format-escape.webp":
    "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoUAAsAPwForE6rJiQiMAgBYCAJbACdMoR4GBwxmM2wsYNEhAAA/ie5SW41+mzVYh1nydkiFD403USVvj75aJFv+tK2I1eZ1whzrZa5X8eLToIx8ZXRYT8A6tAgXIYm+fMYoqatN2iJS/SBkzTYYg7Ya96mBjMnIGr05f1tGg74CotZ776YgAAA",
  "/images/format-party.png":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJQBdgBBewu8DvOpQAAM4M09RQygAZ8FPDoOxEg+msUEurSMdqwHKiJwpcPKRUO5eY0wJlHzjOKIuDLnpbA8Y1jSEHQx6Y4Zn1tk36uwAAAA==",
  "/images/format-party.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAsAPwForE6rJiQiMAgBYCAJQBdgBEMZfWbUGk2LmIAAzgzT0/xNEoapfaTLBABHtP8e4Y+T4kARrFDI7hv4qbdGvPZouXx2KrE8INvfGIw8LOQHznel3IJRlcE3/dQAAA==",
  "/images/game-maatwerk.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJYwC7Ef/gKGCid/aNJmuR0wAAxnGLKjQ+IZTLDfCFnFqD/k6gYLf2GyOa/Bf1twMaiDyURGSWrA3f4ybY33Q0C0HfI0RQeFQrqgwGstSNoBXAeWUskQAA",
  "/images/games-hero-v5-desktop.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZwCAAAcGjus1CmdhpQAA9fyDbPuXQ9xwENve5nEpumNAGB+0u3fXVP9Jf1jUbfpB4pZjRW6o/M8JfVQQAA==",
  "/images/games-hero-v5-mobiel.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZwC/OBtsz/ZJAfW6EAAA9fyDbPuXQ9xwENve5nEpumNAF8bSGOoTqDtbUg5+vn04/waTPc/3BWZHcwAAAA==",
  "/images/games-hero-v5.jpg":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUAAsAPwFqrk6rJiQiMAgBYCAJZwCAAAiN5f3d6Fyb1qEAAPX63kkIP1q6nFQAYJ5ewWl277rpqVcnTIVjscqIJDaSwD6waDdheEvqoIAAAA==",
  "/images/hero-1.jpg":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBOgA/A0lkh8jxSoNdBwAMoEf6TjYUf8J1u+1Kj3D3AzRZJHHkncUGZzN1+fcKfEAmU9eQKjRflldUS7k4NyAN2CTgyyTJWeXrGxwbrtbRUiqhj4n4Vn8qAAAA==",
  "/images/hero-1.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPwFqrU8rJaQiMAgBYCAJQBOgA0a2Ku4yqQjqw0NAAMocvRXA8z/akE6l9M/+9KR6JwZD+uOyn+qG3dpZCGEN20L9SLIzzEJRW1WbItqpPLGmusnj3AN97yKjIXfd41jYs7P5FXoxgAA=",
  "/images/hero-2.jpg":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwAwCdASoUAAgAPwFqrU8rJaQiMAgBYCAJZwAARNir9Or/R+AAy0NJIJgfNiZQNTKhFupxhPwjp/IhZefpQsl4Cmtgf9xcoG9jpkINv4qjI28oBsqAAA==",
  "/images/hero-2.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAAgAPwFqrU8rJiQiMAgBYCAJZQC90BN83hdlGGxlwADLQ0kgmByI93BwoyK+86Wdfaek4luCZ42gEXuwgeMcG9N7ZkHtfVvjbsfKuytgAA==",
  "/images/hero-3.jpg":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoUAAYAPwFqrE6rJiQiMAgBYCAJZwC7ACILYB3lx/SqsLwAAP7m5QCinyFNb7GALrB8Np2/KFaleEZXO5ktUJOilDqBHl4vT1blf7kAAAA=",
  "/images/hero-3.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAAYAPwFqrE8rJiQiMAgBYCAJZwDA3Bh5JBiwl0S7AAD+5uUAn+TvvqYlOwLWPsEjr0qP/BIhisbI7080GYyhDeb0p+bGgAA=",
  "/images/hero-4.jpg":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAAsAPwForE6rJiQiMAgBYCAJYwAAT94Ey33JTeHFwAD+h1H1iQNrmjSXOhaS+WQUo/uqA6Oi+00aKC5USzF8U1qIDlu1iE/bAyV89H+4pN7pgdXV7iPR7sQ5ILD2PoER+qNquFWQk7gA",
  "/images/hero-4.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJYwAAVEa7J2mRvMN5QAD+qcRmbh+tWdgC1JtZsRO4BVWDz+lQkqs4It5u1Qkq7UPO2wjZ8HB97JWBHZV+2BjAnxtdfPwuuhM+v5vGeT6mzDicCmN9aRVZpogAAA==",
  "/images/hero-lobby.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQBACdASoUAAsAPwFqrU8rJiQiMAgBYCAJZwDE2CPTnSRs+BaVnpPcAAD+lOPaVrgZIhzVoFSFbw9W+DpXEK4MKadNEji4A+PE3AM52AA=",
  "/images/hero-v2.jpg":
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZwC7ACPakpbLlaHl0HQA/pF+lT7jWeH3KJkUS6Qz6q14emSkzqW5eH9uJPKeVeBcEimEwTAAAA==",
  "/images/home-essentie.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdABgNrJte1F6fvgAA/bAqmiE+aYZjP1aNqX8a8kS9aZ7xYelYYDJN+N64rsNEeOrRZRiWEmWiLafEK2ZaPNAAJNyHIbqOXxvwWOTM1wWFNMULLbH8xcIAAA==",
  "/images/home-hero-poster-desktop.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAAsAPwFqrU8rJaQiMAgBYCAJZwAAYYGelTXjJtL8MWbAAP5bkS7Fz4PpOHVCg66izX387M6bsV5ALaZEHvlAFVYCRV+AAAA=",
  "/images/home-hero-poster-mobiel.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZwAAYYGelTXjJtL8MWbAAP5bkS7Fz4PpOHVCg66izX387M6bsV5ALaZEHvlAFVYCRV+AAAA=",
  "/images/home-hero-poster.jpg":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJZwAAYXxdJ43RUpv2iAAA/luRgmeLfqm5bwe6i9YhUVSZrNIp2Z03YZGVKLsqQXLgQHyrXAA=",
  "/images/home-inspiratie-strategiedag.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZgCdAywBAsINDxUUxoAAsCmBGM/+4UTJhEG/bU6E4nsnDzW+VuU5EnKuGh8szhXrq668KVMJO8lwro0LDeWa04QQf/56iyVMZh6gAAA=",
  "/images/home-inspiratie-virtualoffice.webp":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoUAAsAPwForE6rJiQiMAgBYCAJQBOmUABYDvmowCpIYuOAAP3b32QFOPuI3hNyrZ1PO5yH/kPFwOO6tr+YmDMh3M3jFZ5MJ8glutIji9i3BDKdAcLjpTMbV+1C5uItMvA1QA3oxNR/cyWVm/S/Ac0AAAA=",
  "/images/home-oplossing-events.webp":
    "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoUAA0APwForE6rJaQiMAgBYCAJQBOgA6fD8Uh3bF0WWoAA/snMVw9FrGSr9Zr/4wME0mGi7ezIgpt3fGZgncsrn0uYQhjkaJ4BbvihoyjWzx9qLG0AMWlmal+z7zwxRFapzg7yeMENpAVB72TH46De8TVXk5I6d4R9gAAA",
  "/images/home-oplossing-virtueelkantoor.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJYwCdACLvyjdrB5fEfTnuAAD+raN2490B9nS2738P+Mrbv9oEcT2E2VFCfUvg9TxRWf+Xi2Eugk++SaqHtgxNyv7KtlNSppNTKorw38AAAA==",
  "/images/icons/bedrijfsfeest.png":
    "data:image/webp;base64,UklGRloBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSGsAAAARR6AmkhQ2+xICoaVicEJEBJ7bNXFwYtu2m5zUEVRZAI+MBBfNJIikg0598/7/MoaI/k8AcNl+B9yHmVkJnMwbwezrqE0GN5WOqlpUv6nB9O+fTQ2L6kdV3VRaq4DJ18HRFwF3p8A9f64ZAABWUDggyAAAABAGAJ0BKhQAFAA/AWyvT6slpCIoDVFgIAlsAJ0yhHmfpu8s9wHUAZIB0rnkVgUHM1YnV/VNvLu4AAD+6k8yC7/sSV0LVqUwWrv/IM/K4+ApxH8m551g3AFhmkPU5WGrGrDgnKwi63mWe9mz1nhf8HJigU+Y+Gd8RLKkZnUD7BNRa3Og2OFh2ObY1hBYzIRvlXmJvFjyHOCfCgNKGjAGpz8X/dHdf+Z60+28Fr/VP+MC3/JvK3s/3/yb4GWFkkdCiNAvGQTKAAAA",
  "/images/icons/bewonersparticipatie.png":
    "data:image/webp;base64,UklGRjIBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSG4AAAARR6AokqQ2eQ5yeCfACRER8HEiSx7cRratNkdYAYboHhRqHCl2E3bIEPMt/F/VENF/IUGCySvA7v/cAHCWpBqYFZTAJzTRyoqOLn+55uuWvzvIe65Zm69bXq45urx1EZ/QBHMoAU6SVAGwve8LAFZQOCCeAAAA8AQAnQEqFAAUAD8BcqxRqyakIqgNUWAgCWwAnTKEtfmCAC3pJT4uq1csAKgupOCAAP4/C8ZsxQx+1nTWfE8K/sY8JIqiu6LbYRmqIjhacSLmpnKxatrT9hevi4r7JEzNio7F/wgM7gMTuJYzMB3R/D0CFtjTsCbGpTYl8wc//TcgPr9+uu4LFgmiNwb2GImmtjMpWyx3ECe72ISAAAA=",
  "/images/icons/communitybuilding.png":
    "data:image/webp;base64,UklGRiIBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSGwAAAARR6AWkiQ4utEnsNFB3FFcRASe21wHTmvbdqJDLAGdg0RSApoKQEEFLHSaeYXzbg0R/Vfbtg0jT+nlDGA+tgaA1cwsAwb7KIL7y0huTsHiSS9P/3qmn2f/e06FMlSKaqQuUleKy9U35IfE1wBWUDggkAAAAPAEAJ0BKhQAFAA/AXayU6snJKKoCAFgIAlmAKwy4j98gAp6wv4zJGYr2Ci6z0fdYAD+selmH6Rw43w41zUgev1UH+Xt/qXVmPFmE9j+biW/igITRAoYaaq49gbxAg9mjWI2H8Q8jXnL3TpSGkbgXQTXaHRd5t/U9s9j5ZVFmGQAde5RSK8jzUHunJe2twAAAA==",
  "/images/icons/netwerkbijeenkomst.png":
    "data:image/webp;base64,UklGRjgBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSG8AAAART6AmkiQ1dxKYs6fsIyIA/9garwentW070SH1gKSJ6LBYHBqFY6HQTLZ5br//UkNE/4UECSavANP/UUUAuyQ1QKegDN6hkUJWsrj86fqPm3/u8Zd35Gg+bn66dnF54RLeoRG6UAasktQAMNy2EgAAVlA4IKIAAACQBQCdASoUABQAPwFsr1ArJaQiqA1RYCAJbACdMoPIOtNoADlFEK/iC+3VVmBfmu2XiuygAAD+DTyXF3WsT7Y0qBPnXltQC1bKUPjTPScHBC8cwXE/9fae1d/ROmsWHeNrkqNwWgWAH4nZ92PWZFI/S7XCtGs4Arbbej8d4O9pTS4MZzw/7O6XMeAqLoVoIKo81CHCaJDwiiotqYDhYp5gAAA=",
  "/images/icons/onlineconferenties.png":
    "data:image/webp;base64,UklGRiIBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSG0AAAART6C2kaQ2+RV4BylEPiIC8Hdfo9MEE1vbZjymPYg2MUVVJWmqKtmBo87e/f6vNUT0X0iQYPIKMLx7FQEsktQArYIyuEIjhax0cvnhutvNj9tfeX/+5nbz4brJ5YVLuEIjtKEMWCSpAaDf1jICAFZQOCCOAAAAkAQAnQEqFAAUAD8BZKxPqyUkIjAYDAFgIAlmAJ0ygAGqAhLiLKx0pxJWZmQAAP5t7HsMwt1PSu30bTm/URhi/2lNP2NONK9D+jOrOoKGF1wVofwZvrDdzvyKMGZCA1M0uXnh31TjdeQaT61Qj7er+s+nne7mtC7Rtu9snWXT9HzXBtftYIIsUD08qAAAAA==",
  "/images/icons/openspace.png":
    "data:image/webp;base64,UklGRhwBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSGcAAAARN6CQjSQ4uBTf3Vksx0VE4HvlwG1s20q1kQKcmIjcY6cChpwvt/8iuKeGiP6rbduGkaf0cgbQXkcOwGJmVgC1vRTC501DYk7B7IkfT/X1TD/P+ffcCmWoFNVIXaSuFJerb8gPia8BAFZQOCCOAAAAMAQAnQEqFAAUAD8BdK5SqyakIqgKqWAgCWoAnTKEfAgJffSpU4SoqZgAAMsEq4ODLf0gVeIHK+fJzUS5Kw0IttwCOL5XViQ0fD76w2Ky0g5mohNgDVa3MPHfJBRT6aRQ2EV7EoVboiV4UXuslGBrdykjwFr0Bqj3u0pcuW4bzQseSc2iMxYS+kH1i+tgAA==",
  "/images/icons/strategiedagen.png":
    "data:image/webp;base64,UklGRiYBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSG4AAAART6C2bRs27Au82WljkD0REeC3NicObGvblnFMPQhVMWVSKZESZJZIB5Z0dvv9Vw0R/RcSJJi8AvTbWkYAiyTVQKugDK7QSCErmV1+uOZ20+v2T96fv7nddLhudnnhEq7QCG0oAxZJqgEYtrWMAFZQOCCSAAAA0AQAnQEqFAAUAD8BcLFSKyYkoqgKqWAgCWwAnTLVQQiAAKnNOoApVzgJVChQggAA90KYhHGOXT5W8L7GKqiEYN+0+b+w4fXrZzyb9MmbiftloiqDsNNAINU7LVfFTEsjP8mNkjRmWB3NQ/YWzlfLw1NxwlJW2mEiW9PvSGhslzd343A8BPuUEtl7PlvwF9wWAAA=",
  "/images/icons/townhall.png":
    "data:image/webp;base64,UklGRiYBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSGoAAAARR6CgjRQ2+AoGYGFJISICz6vqPDixbdtNTuoIqiyAR0YiY2ESRNJBp755/38ZQ0T/JwC4bL8D7sPMrARO5o1g9nXUJoObSkdVLarf1GD698+mhkX1o6puKq1VwOTr4OiLgLtT4J4/1wwAVlA4IJYAAACwBACdASoUABQAPwFwsVIrJiSiqAqpYCAJagCdMsdlpgrWfq9FBravJ6b5WXrAAPjUi4+QYm1lE8OMtO4JQuTRrcYyGqGqJYUSyr64Jobjr/XvBdVKtpOAj/AtNAKpcnRkf+ny6/COzjh54t9LdrnzS3KhXNGPWVUGuscQn4/olpKAw+yWtKj57asE/Vj+AruVNfuCAAA=",
  "/images/icons/trainingen-en-workshops.png":
    "data:image/webp;base64,UklGRi4BAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSG4AAAARR6AkkiQ3ejxnfOzQ+/iICPh4Ni8WTmPbdqpN7CDJ3AMSiaYCUKAz+sdb+Lu3hoj+q23bhpGn9HIGMF5LC8AmIpICvTgK4OPSUYiSN2nilyb/aoa/ZhXNY2EZVorVyLrIutK43P4Gs/qQ+7UEAFZQOCCaAAAAEAUAnQEqFAAUAD8BcrBSKyakoqgKqWAgCWMApyX/5dgi9grJl3buEnqurmTHSybxAAD+wAF3V62WcSBY+4Q/wh5YcK4FiA/RhndlffzUkiRlE/pXBQ+26juf13tcR0T0+AYg5OiEiR51u+JNjZOt0PeIxyJt6fXpsBu2ej+Kyt0vvRUo8guQwe4nrFsYFZ2fEqI16ta5jkAAAA==",
  "/images/icons/worldcafe.png":
    "data:image/webp;base64,UklGRkwBAABXRUJQVlA4WAoAAAAQAAAAEwAAEwAAQUxQSHAAAAARR6CobRs4219VArs5bCgWEYHnhdYGbiPbdpqDLYEh9EghISUQU4G8VAGj2N/C/6WGiP4LCRJMXgGW9d4DcJKkAhgVlMA7NFHJig4uf7n9180/9/i755at+bj55cqDyysX8Q5NMIYS4ChJBQDLeu8AVlA4ILYAAACQBQCdASoUABQAPwFwrVCrJiQiqA1RYCAJbACdMoPEKcIszvgABZtYw2fUIb1uQ/xBBDN9AAD+5wm4NYItL+94fMgx6yAG2drubt/xgE4iZ/bCc+HtcFPuMyKOTdcGpDiOqbvKm9KtoqcUwqslnP+2DEgZF81DTdsi3VOvzGBKSVrPy5kZgpBTf++alt1XfW9ahcjHYJKhUFtzH2oJjcG0qXzlG0y9f+Tf48Z2IaYNRUS22OAAAA==",
  "/images/inspiratie-escape.webp":
    "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZACdMoABdhxO3pC0q5ugAP62oj14YII7Quw96mEBczTFkv4fYw+8tR0Amb7hZlgvQPqEF/hh74Wj9Gl3TKDggWc78HDgVeaXYBbLWAxp18KVsXtXL88FME0DhK/tzsHObjL8UH8gvgAA",
  "/images/oly-bar-milano.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBOmUAA1CkFIAHAYJ4AA/j5AtY0lzmpIVfZNf+xNwfPhRqcSmLbxhXk3R0fVCc/ePfGr9Keql1ummkR5wIpwOV+ZuMMpu+NrPYydNrKoCA+Gw7WZFGWowAA=",
  "/images/planning-1.png":
    "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoUAA0APwFqrE8rJiQiMAgBYCAJYwDA3CIC+KPy/JYUHTFqIAD+ScJrlYRe6xQRu2kmHIwlqR5vnzxUubUr60rTxuUNwR+bd2J75jU2nFmVtNalBdkd2RBt3/6FJ3xH3z7e36oMzx3cQf34n0f+0YYYJ02r+iP5WtQVd5qdswSNTMgea9GJIAAA",
  "/images/planning-2.jpg":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA4APwFqrE6rJiQiMAgBYCAJZwAAWlPFanVKHnqocAD+6oUIqsNfAaxpO6OWEq/mfxNCXPxt/aeJfdcDxawo3iWYe4GYTiE5/F4W5FBqeEAA",
  "/images/planning-3.jpg":
    "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoUAA0APwFqrE8rJiQiMAgBYCAJZwAAXvc/HRyxSqQ8YRkKAADif26LPzqvgZ4gpn91L3+yiH2K4glu8QXvLKdQGK2JEDBfMzoypK6cRk/PCZ329tG28iZYM/HvwiFOGCv5Yst2/yDGtgF07xWJTeyvTjSigTQt6Zx1AAAA",
  "/images/planning-4.jpg":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoUAA0APwFqrE6rJiQiMAgBYCAJZAC7ACE9sfeyVNTdivWfAAD+6oPFzKdfGTXbyHVU/cRs4pv8N4KHfe2KGJTNluFk5y9lJa+REdrURpCtfi7afYPbtdIPPgAAAA==",
  "/images/platforms-hero-v2.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJZQDE2CBruDMPFgSalxd1kLzAAPlyixvnPIRHL0Duom6lplu7Wr18h8h4G5uvklvGjzIE4EeNxUDTPsywiXVNznBstdTTSVnw4x4f7iB0IcQUAAA=",
  "/images/ravenhack-crisis-v2.webp":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAAsAPwFqrk8rJiQiMAgBYCAJZQAAW7kY2WUIwvE4AP68jUlTEazCzEpzgpjaXvfPbrrL0ukKb5e68AXJSdlw0AA=",
  "/images/ravenhack-doorbraak.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoUAAsAPwFqrU8rJiQiMAgBYCAJYwCdAB6yBXszfXHYenOOfAD+uwimbZ5F1a7HH4MaAgR+0N0Z7jcFmTIcXYVdxiWTY44EBMP0+48of8LUgvNtSzZWh1uXtM/lkrGG01FOAAAA",
  "/images/ravenhack-hero-v2.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJbACdMoADS15rWAWGcesrugPygAD+5kMVn60EPK9KnaVcrU4hFHo4wXoVWBrrV/9+53r/WalzelqKJgcnT1V5QdPWbgsEX1cFhlLkPdxxOSZM8X7Yu6Om/pF4AA==",
  "/images/ravenhack-hero-v3.webp":
    "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUAAoAPwFqrE8rJiQiMAgBYCAJbACdMoADS15rWAWGcesrugPygAD+5kMVn60EPK9KnaVcrU4hFHo4wXoVWBrrV/9+53r/WalzelqKJgcnT1V5QdPWbgsEX1cFhlLkPdxxOSZM8X7Yu6Om/pF4AA==",
  "/images/ravenhack-hero-v4.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJaACdMoADf74c/Ns32q4AzKNQAP2wimAMUPbZOxyU+gu75MS/yeyyUoY/knRwWjMWHCYygmdfv0SWNEPgMK544mfo0ye4+VH++nNYvGwvTSaAAAA=",
  "/images/ravenhack-hero-v5.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAAsAPwForE6rJaQiMAgBYCAJaACdMoR4GCPfm2ci5yD/nOAA/r9qJMVm8KZR8sDmW/Clx4kS5N/iMzGCXET4L20J7vuBCHH2Ick6af4WcKnoJCWTxm4xR5U2dLSGOFQQnUfbIa3UAAAA",
  "/images/ravenhack-hero-v6.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJaACdMoR4GB6cnd85opJ54AD+v2okx07wrcPlE2DdA7rRLk3+Izwr87bLAhuVyZC8EoyT07G6lBBtYEzr9BOicFAN+isBiQjBqSD7cFZfGobmdoAAAA==",
  "/images/ravenhack-hero-v7.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPwForE6rJaQiMAgBYCAJaACdMoR4GB26hM3n0YgAAP6/aiTHTgBXkX3A8UMXNSsmCzniR3gJw3Kh7mFrAMBg0tx3ksTsYCIYDGX+16USPW9/14gMHLyQbq1ZIiEMabyeElFSp9wAAAA=",
  "/images/ravenhack-hero.webp":
    "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBACdASoUAAoAPwFqrU8rJaQiMAgBYCAJbACdMoADQV4q+Thy49ip3XAAAP7dSFFVUVJpP8nx3jm3MjdG5ElNOAQOnPILwrkUsxPj95eUIvbd9E9l9vVXlB0+Ko/K+Sk1jPDciHhGbcRLfIqRuiW3738qGsISPu6bAAAA",
  "/images/ravenhack-video-poster-en.webp":
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJbACdGurAWbstEVO24o/+GQPgAAD+7O16rXJNVb84eduAyVAptosCETUicLjR/mlhTPydQCIkZySk9/+u5A26j2cbXYoOUhvsSQ6tJpcsNprEUnCGDajucWEnh9Qrj5w/ozL4fzDgAA==",
  "/images/ravenhack-video-poster-nl.webp":
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJbACdGurAWbstEVO22jcaqcSAAP7s7Xqtck1Vvzh524DJUCm2iwIRNSJwuNH+aWFM/J1AIiRnJKT3/67kDbqPZxtdig5SG+xJDmQk5WOulKQ/NOzzP1loZI5Md7UK4+cP6Mr6CauAAA==",
  "/images/spatial-entree.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAAkAPwFqrE6rJiQiMAgBYCAJYwCdMoACb2TTLVq/M7WwAP6RPFtKsO6S8R9HQJqVaY2hIHAuCT897CAkrIAjnjhEmImYqeafUA+gYoFuldCxq5AAAA==",
  "/images/spatialchat-hero-v3.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJYwAATrNUwXgVCIoHCXwAAP6cDZN2iCByJ0TGUgtgICTUkZ5VIfsep0cRlp/PvF4FrgtStMtdy9XV+11t9qpimfWOdno60aKT7ZNGzy/lkLsg4mNj9nAA",
  "/images/spatialchat-video-poster.jpg":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJYwC/OB9eo6vwUYY0OcAA+DMMcGuSgSZW4hJO16yT1YlkpmJ+UlyvbJTKhgsrPEwbMN3lj8wseZwRetYFJ6dJOtLPgLWagaQvKurfMfLuOhn0T3u1awAA",
  "/images/strategy-1.png":
    "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAADQBQCdASoUABQAPwFyr1KrJqQiqAqpYCAJbACsMzQ1Z2HhKgFdJVu42IJfr4/LYu5k7GBVE1wAAP7draQt6NUETmyUzY/DyRxJJSn8oudAwDI5NjZPN2g8LN9dVpdWdPXCwwLRV9ifu9qcRtn1R2qRnXpbY+4j9dnhM2eZBAbi3fz5nlaxoWzhz0ysAQ4vXezQ8lYgJJMKHPw28TVvy4ZycLg5b9RPKtGaB+wTF/MKVJz0nry7qlYkh+pFqRRbpWcRMlaPUd7p0xG2AAA=",
  "/images/strategy-banner.jpg":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJYwAAV9K3Ppw1bvcqmDnAAP5nM51ZdYPD3u4GfIKiSMwvqm7GMikkovg9HG6gp4cr/wOaDq/Zp0WGx18e1r8BPL3QtAWOgOJmS1n9ByKDtLvUAAA=",
  "/images/team-emilie.jpg":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUAA8APwFqrE6rJiQiMAgBYCAJYgAAV64XKgBqy4TXtUgAAP7svqKWzZEfqx2FdARCce+6tkh9rHwR4HaV1pb+jQ2d1cS44tZQ1bmIG496rKJqcv5MAA==",
  "/images/team-group.jpg":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZ1e1wC1AAALD7/7KEAD+7zXuXhMExnH1OfIIXPlcnpFoUicK3VEp5F83TEVfWN3XkMvjhNgUs9CK4ZEb/EXGsIYr7pexyDDbd5Ux3QgAAA==",
  "/images/team-mm.webp":
    "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoUABEAPwFysFIrJqSiqAqpYCAJbACxHyXwABULRfGmMPftBZnXAAAA/sNL7qc8JijH31/NHc6e5gAWLIUXrJQ3b7yVIS9QQNwffsbvf8o75Hw4RYWGgGepwYr7sAQSHYlVM6yf8kOUBBdLdrDvTXuxc57hg8qFLyszYbvAEHOrLJF0neQ8YB8mnAAAAA==",
  "/images/tech-hulp-hero-poster-desktop.webp":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAAsAPwFqrU6rJiQiMAgBYCAJZwDG9CGgfSLe4qOjoAD+78VFVr9LWxeXF2rGIywYmOFEePFtSIC9+U/qR1h93Hxg3AaInUVW7PF6OGBIq4xAhddgXFo6AAA=",
  "/images/tech-hulp-hero-poster-mobiel.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAAsAPwFsrU8rJiQiMAgBYCAJZwDG9CGgfHcSaq884AAA/u/FRVa/S1sXlxdqxiMsGJjhRHjxbUiI5DSUY4/KJCpr6XM0wIaniFpIv0IcBtdGRdyYAA==",
  "/images/tech-hulp-hero-poster.jpg":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZQDG9CGnxm9t6zh1sAnAAP7v0fTlQCnEctqoZC82ETTmQZQfEXK2mvJXGbOJ7tH/9B2xXzPK3nw0i1kJyOw4yLuTAAAA",
  "/images/tool-bingo-v2.webp":
    "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBACdASoUABgAPwFssFErJaSisBgIAWAgCWwArAAQXXuwWD4sYIOoq2NTwYAAAP7vw4yO1MmfHJjkZMaWidlIu261kvVVdwXrsIGW8Qvm7oqLYJIhlxnFTuuM1Ob/zABWDnHtnuyVoFuSGIw0g3XT4cfnTnS6000QlE6+PG1T0/vwZ4ABPhB2AAA=",
  "/images/tool-inspiration-cards-v2.webp":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoUABgAPvVirE6qpaSiMAwBUB6JQAAKUWT0WfkuwtP1XRQNWgvAGHCIAP7Kmii1h1Umbb/9jRzDKa+sSJXSJYkYvqJMIjslMfAARd9EcUXe+Rb+2dwd4bLNGHq4kn6GSbRTkbw03aaptDz02aCwhQwAAAA=",
  "/images/tool-storytelling-v2.webp":
    "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQBACdASoUABgAPwFwrVCrJiQiqA1RYCAJZQDOdA9ouECZ+R/OyzdaXfAHsF9LiAD+6F+X9T5550VdL+MvwpT+KOGJHBpWFyCbKUWVSaXhyAq6gurpQ1ii5HBy1DwAN5pXxTfnAe0NBmQr+pYTTPuSTHkQwJKYGwotwAAA",
  "/images/tool-wheel-of-fortune-v2.webp":
    "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACQBACdASoUABgAPwFysVIrJqSiqAqpYCAJbAC7ABEcmtFMuStzB0qxOvoGMIAA/u03aSuONXxT2GibQWVWz+qosE9WUVoPYfVsP2uEsUDlQFrjnQc5RUNbDio0cEFlpvIDoi9srNI6gvH67/fFeZFuW03tyqFy0dxYTZV1t3LufngA",
  "/images/tools/inspiratiekaarten/achterkant.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQBACdASoUABwAPu1gp06ppaOiN/qoATAdiWcAAF2k6zcwycvrEBmsWaiwiIAA/ngaCKCGy1x33NzVfxgykYX4KvA5TGr5CE5GscCuhNmSdcXn6n31+5+7mHG5EXh/PWjaf/iB4AA=",
  "/images/tools/inspiratiekaarten/en/achterkant.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQBACdASoUABwAPu1gpk6ppaOiN/qoATAdiWcAAF2k+zXm3raAuXnRajQwogAA/ngaCKCGyzZNpT4Si+t182KM/9CpwsMrRFr6herI4syvjEW5XG73TI4xctrRZooD5KHgZaMCAAA=",
  "/images/vergadermacht-boek.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA0APwForE6rJiQiMAgBYCAJagCdACPxvI3A2Nq1HAD9/AOiLJ6QCpe5Fzt6puOqKKCXl+rYryNag4l2vOpnBRthwDqrrRSWoM7g+OJlG+AJEv+8Mg30uZsrWBCkNCCTy4DuU8AAAA==",
  "/images/vo-clubhuis.webp":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJQBOmUAA1CkFIAHAYCAAA/j5AtY0lzmpIVfZNf+xNwfPhRqcSmLbxhXk3R0fVCc/ePfGr9Keql1ummkR5wIpwOV+ZuMMe3GqqXyk0GpIsiNmqf/KD8AAA",
  "/images/vo-community.webp":
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJQBYdhA0V4zbq4fAQoAAA/Io6MOUjQGzKuQTRtz7/WaJ3vFwlNozOTpV52SvfqMxc054fsi//YNaLhhkRndQROP8TIY+1rs7tDvPXxKS0NQ9Cea9eAA==",
  "/images/vo-fundament-v2.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJZwDG9BuVpXulfFNK3EUAAAD4WcBM3OdX4d9ewcaPJw9x0xxcpr9ab4WSXdneLTEmKJhKPGHVwMzHZnAkBUJ5r5gAAA==",
  "/images/vo-hero-office-desktop.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZQDDNBss01g3KTOoYTAA4C8jRN6YPUZ7Cvtybr5iO1uJ+wiGFF1HbV06sYjo2SdpPj4pZRw/mf35lgc8EQTi0D/ACBUW8sXOoKAFqQAAAA==",
  "/images/vo-hero-office-mobiel.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZQDDNBss01gjZC0jWAAA4C8jRN6YPUZ7Cvtybr5iO1uJ+wiGFF1HbV06sYjo2SdpPj4pZQKvpndjgfVkGk+Q/V9zWgCbTkfAAvlT58dvIAAA",
  "/images/vo-hero-office.jpg":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoUAAsAPwFqrE8rJiQiMAgBYCAJZQDA3CKlWUI9BZ86doIQAADgMcF/MQgE5tTyDfjsJrM8akC/pa6rsPQgSNG0TnzA0oJLcEnSH+yDbpt6RvPmblr8jnOHDU4xqAAA",
  "/images/vo-hub.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZwC/OBjXGlRZYukAAP5n28DiiOpY3AVravwyp3eLEsWrfe+kUEJtX7nY10Kv7ftb6Z+cwcnpaolvCmP0BcySUa+n+t9l5gWVqYqAAAA=",
  "/images/vo-huren-v2.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAAsAPwForE6rJaQiMAgBYCAJYwCdAB9Rk98xlbY5ndmAAAD+kbg897SmXByIX1MRxICoGKW4xc0aMUsGRvLEs0cwoCSlte9ie2Xu/WOfYdmfSNEGp8/TdYJJ3h8zttVvxkAVMMFuokkAAAA=",
  "/images/vo-museum.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJYwDCgCHSwY+tTIO+rgAA/NkUlaLEX71UEC5Tf2paZHpVMVjfMVQiu2kuIrFnUBdv9fKOsm3lyzfpKpzvNJjbTAIxTU1wccuwe6ICVvplkpAAAAA=",
  "/images/vo-project.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJYgCdMoAC4SNUgn15SIAA/n6T3ILNS1nY99j824s0fZuLnyvIKz2XCSAAQczG+H7vb63bKExf7QwaQ8OnbOkWvuflx9bq54st3cAJ8rwAAA==",
  "/images/vo-thuisbasis.webp":
    "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBACdASoUAAsAPwForE6rJiQiMAgBYCAJbACdMoR4PoADUERwsFA0Er5PgAD+sY5sM003w/Ca/8JYo2te66Vh46f0LDdeOc2a8co5KzfdEcZY9B4IM41tsqzDXBO+BHjx9/V/udEgN/1NO+N38KqLO/2AmhnVy4AAAA==",
  "/images/vo-zaaltje-v2.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAAsAPwFqrU8rJaQiMAgBYCAJYwC/OBmjSPZUMHB8jfoAAPZU297aj3E4Ic3AnRLkRLdAegpIAs6trZsQzYibINn/NuI6XDcFVc74nxYEQZVTVb/jzwAA",
  "/images/zaaltje-bezinning.webp":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoUAAsAPwFqrU8rJiQiMAgBYCAJYgCdMoACsJkbMBr0ni+AAP5aBLons3L03geRrNCqwxmASAqJL/o7KPsYUwkKO1WZCKUT6dA0bUv9Ibh4PtkwAAA=",
  "/images/zaaltje-bosdag.webp":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQBACdASoUAAsAPwFqrE6rJiQiMAgBYCAJYgCdMoADUFq/vJJYBJIK4AD+pbhvPffSYOnC89dtulgLqE9FFcTkO8+s6sCsFfkLqNzq2Rc5j42OJ0VQrAAA",
  "/images/zaaltje-creatief.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoUAAsAPwForE6rJaQiMAgBYCAJZQDA3CHKLiP0Ky5T3gAA/NkUlaLC31/arCY3bcEJDtAO0Ou0/rzzX4W3jSECkuxp9gO44fNJja2tslqUn+6gTKT+mePsuJoAAA==",
  "/images/zaaltje-heisessie.webp":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAAsAPwFqrE6rJiQiMAgBYCAJZQAAW6WvGQvzPHRIAAD9Owh67RHmp5v9tDpg0IzkP7KmPsbNO2m55SuD5t/C99UXdg0EdjoRcAAA",
  "/images/zaaltje-strandhuis.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAAkAPwForE6rJaQiMAgBYCAJQBWAA+YTyKYgyTimAAD+XuQ7R/s4YypdBQiKmJO6mC0oQJSM725Um5mcRl0Mg7gPKqu33f0FfaZ8Wbd87TlKB3NrSCAA",
  "/images/zaaltje-werksessie.webp":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPwFqrE8rJiQiMAgBYCAJZwAAQtpnqsUw5VUnpcAA/tbSpB0H9hCTYHaT0A5XKPO6F8fZACTFoxyXbZh/HA/KUsHnpwktSG/VTQeFTfbgAAA=",
};

/** De miniatuur bij een beeld, of undefined als we er geen hebben. */
export function vervaging(src?: string): string | undefined {
  if (!src) return undefined;
  return VERVAGINGEN[src];
}
